#xAuth config file.
#Most of these setting are safe to configure, as long as you know what your doing.
#xAuth has an config error checker that will fix most issues.

#Type of authentication?
# YML or MySQL?
autentication-type: YML

#Allow moving when loging in?
allow-movment: false

#Use aysnc task to login? (Huge performamce boost, but may cause a half a sec tick delay when reciveing password)
#Only for MySQL
use-async: false

#Enable database checks? (Recomended, checks every couple of ticks to make sure the database is onlie, errors, ect)
#Only for MySQL
database-checks: false

#Cache logins? This will let you download mySQL data and put it in a YML, so next time the same player connects, the server won't have to query.
#Disatvanatge: Removes ability to change password.
#Only for MySQL
cache-logins: false

#Enable password changing? (Will be disabled if cache logins are enabled)
enable-pass-changing: true

#Debug-mode? (Notice: You can't turn this off on beta releases from xauth.com)
debug-mode: true
