name: xAuth
author: xFlare
main: xFlare\xAuth\Loader
version: "1.0.0"
api: [1.8.0]
description: xAuth protects your server and adds authentication.
commands:
    login:
        description: Login.
    register:
        description: Register
    changepw:
        description: Register.
    unregister:
        description: Register.
   
    
