#xAuth config file.
#Most of these setting are safe to configure, as long as you know what your doing.
#xAuth has an config error checker that will fix most issues.

#------------[Authenticatin Settings]------------#
#Type of authentication?
# YML or MySQL?
autentication-type: YML

#IP auth or type password everytime you join? 
ip-auth: false

#Use aysnc task to login? (Huge performamce boost, but may cause a half a sec tick delay when reciveing password)
#Only for MySQL
use-async: false

#Enable database checks? (Recomended, checks every couple of ticks to make sure the database is onlie, errors, ect)
#Only for MySQL
database-checks: false

#Send users a message below the hot bar letting them know what to do? (Recommend you keep this on)
hotbar-message: true

#Enable password changing?
enable-pass-changing: true

#Block simple passwords?
simple-passcode-blocker: true

#------------[Authenticatin Settings]------------#


#------------[Auth Events]------------#
#What to allow/disallow when not authenticated?
allow-movment: false
allow-commands: false
allow-block-placing: false
allow-block-breaking: false
#------------[Auth Events]------------#


#------------[General]------------#
#Anounce player join? xAuth let's you choose whether you want "player has joined the server".
player-join: true

#Anounce player quit? xAuth let's you choose whether you want "player has left the server".
player-quit: true

#Show there auth status when not logged in? Username: "[Not-Logged-In] Steve"
show-username-auth-status: true
#------------[General]------------#

#Safe mode, if xAuth is not enabled due to some sort of error, don't let players do anything? (Prevents impersonators)
safe-mode: true

#Debug-mode? (Notice: You can't turn this off on beta releases)
debug-mode: true

#For internal use only. Do not edit.
version: 1.0.0
