#xAuth config file.
#Most of these setting are safe to configure, as long as you know what your doing.
#xAuth has an config error checker that will fix most issues.

#------------[Authenticatin Settings]------------#
#Type of authentication?
# YML or MySQL?
autentication-type: YML

#IP auth or type password everytime you join? 
ip-auth: false

#Use aysnc task to login? (Huge performamce boost, but may cause a half a sec tick delay when reciveing password)
#Only for MySQL
use-async: false

#Enable database checks? (Recomended, checks every couple of ticks to make sure the database is onlie, errors, ect)
#Only for MySQL
database-checks: false

#Cache logins? This will let you download mySQL data and put it in a YML, so next time the same player connects, the server won't have to query.
#Disatvanatge: Removes ability to change password.
#Only for MySQL
cache-logins: false

#Enable password changing? (Will be disabled if cache logins are enabled)
enable-pass-changing: true

#------------[Authenticatin Settings]------------#


#------------[Auth Events]------------#
#Allow moving when loging in?
allow-movment: false
#------------[Auth Events]------------#


#------------[General]------------#
#Anounce player join? xAuth let's you choose whether you want "player has joined the server".
player-join: true

#Anounce player quit? xAuth let's you choose whether you want "player has left the server".
player-quit: true
#------------[General]------------#


#Debug-mode? (Notice: You can't turn this off on beta releases)
debug-mode: true

#For internal use only. Do not edit.
version: 1.0.0
